### ISSUE TITLE
Blank page when enabling the plugin and links

### ISSUE THREAD

**Issue by MasterIO02** [LK608/OG-Scraper#1]
Hi, I installed your plugin and phpscraper using composer, but every time I want to enable or disable the plugin via the admin interface the page goes blank until refreshed. When the plugin is activated all links are not redirecting and are blank too.
Need to mention I am using Yourls 1.7.9 on Docker.

Any thoughts of what the problem is? I haven't seen any error logs from Yourls.

**Comment by LK608** [comment]
Hey, 
I'm sorry to hear the plugin isn't working for you!
Did you change the path to the autoload.php file in line 21 of the plugin? It must be the path from the root of your YOURLS installation.

Have a nice day!
Luke

**Comment by MasterIO02** [comment]
Oh, I only checked the phpscraper path. I added the correct path to autoload.php and now it seems like the plugin loads when clicking a link but I'm now getting
`Fatal error: Uncaught Error: Class 'Goutte\Client' not found in /var/www/html/includes/vendor/spekulatius/phpscraper/src/phpscraper.php:87`.
I installed fabpot/goutte with composer but it still throws this error when navigating to any link.

**Comment by LK608** [comment]
Hmm ok... This shouldn't be a problem with the plugin, but with phpscraper, right? Have you tried reinstalling phpscraper?

**Comment by MasterIO02** [comment]
I reinstalled my docker container with phpscraper and it works now.

For my usage of this plugin I needed to add meta tags for og:video to get embeds on Discord, like Streamable does.
I don't know how to code in PHP but managed to do what I wanted pretty easily.
The links I'm shrinking are raw mp4 videos so I could make og:video:url just the full host url.
Since I only use YOURLS for mp4 video file sharing I don't care if this breaks other links. Since I have the video thumbnail at the same path as the video with the same name I just had to change the extension.
Here is what I've done: 

`$full_url = 'https://' . $parsed_url['host'] . $parsed_url['path'];`
`$thumb_url = substr_replace($full_url , 'png', strrpos($full_url , '.') +1);`
`$filename = pathinfo(parse_url($url, PHP_URL_PATH), PATHINFO_FILENAME);`

And I added/modified this to the meta properties: 

`<meta property="og:title" content="' . $filename  . '" />`
`<meta property="og:type" content="video.other" />`
`<meta property="og:image" content="' . $thumb_url . '" />`
`<meta property="og:video" content="' . $full_url . '" />`
`<meta property="og:video:url" content="' . $full_url . '" />`
`<meta property="og:video:type" content="video/mp4" />`
`<meta property="og:video:width" content="1280" />`
`<meta property="og:video:height" content="720" />`

Maybe it could be implemented properly? Anyway, thanks for your help and this plugin! (this is not an issue anymore, you can close it)

**Comment by MasterIO02** [comment]
Well, I spoke too soon, when using the plugin with or without my modifications, when the destination link is a large file it tries to cache it, resulting in:
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/includes/vendor/symfony/http-client/Response/CurlResponse.php on line 298`

I could increase the memory_limit but the video files could weight +1Gb so that's not ideal.
What could be the cause of the caching?

**Comment by MasterIO02** [comment]
Found out the issue. I deleted phpscraper and everything else referring to it and it works since my Open Graph tags doesn't need it. Makes sense, I don't know why I haven't thought this before.
Anyway, thanks again for this plugin, hope someone will find this issue useful.

**Comment by dcapape** [comment]
> 

This is what i did:

`$headers = get_headers($url, 1);`

` if (strpos($headers["Content-Type"], 'video') !== false) {        `         
`echo '<meta property="og:video:type" content="'. $headers["Content-Type"] .'" />       `                                                                                             
`<meta property="og:video:url" content="' . $url . '" />              `                                                                                                               
`<meta property="og:type" content="video.other" />';          `                                                                                                                       
`$title = pathinfo(parse_url($url, PHP_URL_PATH), PATHINFO_FILENAME);           `                                                                                             
`}              `                                                                                                                                                                     

`echo '<meta property="og:title" content="' . $title . '" />       `                                                                                                                 
`<meta property="og:type" content="' . $web->openGraph['og:type'] . '" />      `                                                                                                      
`<meta property="og:url" content="' . $web->openGraph['og:location'] . '" />          `                                                                                               
`<meta property="og:image" content="' .  $image . '" />   `                                                                                                                           
`<meta property="og:site_name" content="' . $web->openGraph['og:site_name'] . '" />         `                                                                                         
`<meta property="og:description" content="' . $description . '" />';   `
